### ISSUE TITLE
API URL individual parts

### ISSUE THREAD

**Issue by gokdeemir** [bounswe/bounswe2019group7#100]
Everyone will do API URL(documented) of him/her part. Then, Alperen converging them to Wiki page. After that, Kutay will add the wiki document link to the frontend.
Deadline: 11.05.2019, 23:59

**Comment by safakozdek** [comment]
I think we should create a subtitle on the sidebar of wiki and list everything related to practice-app and API under that title. In that way things could be more organized and good looking.

**Comment by alprnbg** [comment]
> I think we should create a subtitle on the sidebar of wiki and list everything related to practice-app and API under that title. In that way things could be more organized and good looking.
I can do that while transferring the documentation to our Wiki page.

**Comment by alprnbg** [comment]
We should also write _How to Install and Run_ section other than individual documentation.

**Comment by safakozdek** [comment]
> We should also write _How to Install and Run_ section other than individual documentation.

Yeah but this will not be exactly as it is on EC2 device since we do not publish database information on Github, even though it works fine with built-in database SQLite. However, I think this should be done.
