### ISSUE TITLE
Deployment of the backend to AWS

### ISSUE THREAD

**Issue by SKutayKilic** [bounswe/bounswe2019group7#133]
At the end of the week, the backend application will be deployed to AWS.
Deadline: 14.10.2019 @ 23:59

**Comment by safakozdek** [comment]
Error while deploying:
no main manifest attribute, in /home/ubuntu/cloud.jar

Please debug this problem. @SKutayKilic @gokdeemir @memhak @Oguzhan09

**Comment by SKutayKilic** [comment]
Done
