### ISSUE TITLE
Research about Git version control system

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2019group7#2]
Research about Git version control system will be made.
- [x] Esra Yılmaz
- [x] Alperen Bağ
- [x] Alican Şafak Özdek

**Comment by gokdeemir** [comment]
Done

**Comment by alprnbg** [comment]
Araştırmalarımız sonucu elde ettiğimiz bilgileri derleyip, wikideki GitHub tutorials sayfasına yazmamız gerekiyor, nasıl yapalım? Herkes ayrı ayrı sayfaya kendi bulduklarını yazsın mı, yoksa birisi bütün raporları alıp kendisi mi düzenlesin?

**Comment by safakozdek** [comment]
A Useful Resource for git: https://guides.github.com/introduction/git-handbook/
