### ISSUE TITLE
Update profile end point returns 500

### ISSUE THREAD

**Issue by Anxeal** [bounswe/bounswe2019group7#233]
**Steps to reproduce:**

- Call either `/user_profile/update_basic_profile` or `/user_profile/update_trader_profile` with the appropriate authorization token and data

**Observed behavior:**

Returns 500 and the following message:

> Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction

**Expected behavior:**

 Returns 200 and the resulting profile info after update

**Comment by anilcankara** [comment]
Solved with the new deployment.
