### ISSUE TITLE
Favorite Git repos

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2019group7#3]
Favorite Git repos will be determined and introduced briefly by all members.

- [x] Seyfi Kutay Kılıç
- [x] M. Emir Gökdemir
- [x] Esra Yılmaz
- [x] Merve İlik
- [x] Alperen Bağ
- [x] Alihan Çelikcan 
- [x] Alican Şafak Özdek
- [x] Nazım Berke Metin
- [x] Kemal Duru
- [x] Ahmet Emir Kocaağa

**Comment by alprnbg** [comment]
done

**Comment by safakozdek** [comment]
Done

**Comment by liberbey** [comment]
done

**Comment by SKutayKilic** [comment]
Done

**Comment by gokdeemir** [comment]
Done
