### ISSUE TITLE
Refinement of requirements

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2019group7#34]
Project requirements will be refined depending on the feedbacks and answers given by the customer.

Deadline: 27.02.2019 @ 23:59

**Comment by alprnbg** [comment]
Could someone review the new requirement page?

**Comment by liberbey** [comment]
I think it is really better now, thanks!

Using ')' after enumerations seems unnecessary to me and visually I did not like it.

1.1.1.1.1.) All users shall have a “Profit/Loss” section. &
1.1.1.1.3.) All users shall have an “Events” section.

could be written together.

1.1.4.3.) Basic users and trading users shall be able to share their portfolio in their profile page.
1.1.4.4.) Basic users and trading users shall be able to follow other users shared portfolio.

this 2 can be also written together.

1.2.5.1.) The system shall be able to recommend people to follow.
1.2.5.3.) The system shall be able to recommend trading equipments to follow.

also this 2.

2.5.1.) System shall store user information on database.
2.5.2.) System shall store trade equipments on database.
2.5.3.) System shall store follower relations on database.
2.5.4.) System shall store portfolios on database.
2.5.5.) System shall store user histories on database.
2.5.6.) System shall store user preferences on database.

and lastly these can be written in a single sentence. If you agree, I can make the changes.

**Comment by alprnbg** [comment]
It is okey for me. You can make the changes, if you want. Thank you :)

**Comment by liberbey** [comment]
Done. If there is no any other reviews, we can close the issue.
