### ISSUE TITLE
Personal spaces on wiki

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2019group7#4]
Personal space will be created on wiki.

- [x] Seyfi Kutay Kılıç
- [x] M. Emir Gökdemir
- [x] Esra Yılmaz
- [x] Merve İlik
- [x] Alperen Bağ
- [x] Alihan Çelikcan 
- [x] Alican Şafak Özdek
- [x] Nazım Berke Metin
- [x] Kemal Duru
- [x] Ahmet Emir Kocaağa

**Comment by safakozdek** [comment]
Done

**Comment by alprnbg** [comment]
done

**Comment by gokdeemir** [comment]
**_Done too_**

**Comment by liberbey** [comment]
done

**Comment by SKutayKilic** [comment]
Done

**Comment by esrayilmaz7** [comment]
Done

**Comment by merveilik** [comment]
Done

**Comment by nbmetin** [comment]
Done

**Comment by safakozdek** [comment]
All pages created.
