### ISSUE TITLE
Preparation of Class Diagram 

### ISSUE THREAD

**Issue by gokdeemir** [bounswe/bounswe2019group7#45]
Preparation of Class Diagram task is created 

Class diagram will be prepared. Before the preparation the assignees research about Class Diagram. Then there will be a meeting on Sunday to preparation.

Deadline: 10.03.2019 @ 23.59

**Comment by alprnbg** [comment]
We can look that slide, it would help.
https://courses.cs.washington.edu/courses/cse403/11sp/lectures/lecture08-uml1.pdf

**Comment by liberbey** [comment]
Needs Review.

Link: https://www.lucidchart.com/invitations/accept/79fc9d73-0cc7-4e5c-b4c9-cf2e8150b6fb

**Comment by safakozdek** [comment]
We should add a function like getUserInformation(params) to receive information about users' profile. It should consider public/private profile type and return necessary information such as user name, success rate etc.

**Comment by safakozdek** [comment]
We need to add parameters to followUsers() function. It should take 2 different user ID for identifying the user that sends follow request and the user that first user requests to follow.

**Comment by alprnbg** [comment]
> We need to add parameters to followUsers() function. It should take 2 different user ID for identifying the user that sends follow request and the user that first user wants to follow.

I added necessary parameter to _followUsers_ method. Actually, user ID is enough as parameter, because this method will be called by an BasicUser object, which means we will know the user who want to follow.

**Comment by alprnbg** [comment]
> We should add a function like getUserInformation(params) to receive information about users' profile. It should consider public/private profile type and return necessary information such as user name, success rate etc.

Added.

**Comment by safakozdek** [comment]
> > We need to add parameters to followUsers() function. It should take 2 different user ID for identifying the user that sends follow request and the user that first user wants to follow.
> 
> I added necessary parameter to _followUsers_ method. Actually, user ID is enough as parameter, because this method will be called by an BasicUser object, which means we will know the user who want to follow.

Great

**Comment by alprnbg** [comment]
I think we can close the issue
