### ISSUE TITLE
Research on Use Case Diagram

### ISSUE THREAD

**Issue by gokdeemir** [bounswe/bounswe2019group7#46]
Research on Use Case Diagram task is created.

The assignees members research and study about how use case diagram should be, what the requirements are, and like this. Afterwards, they will review Use Case Diagram of our project.

Deadline: 16.03.2019 @ 9.00

**Comment by alprnbg** [comment]
The link of the use case diagram. 
https://www.lucidchart.com/invitations/accept/261e3b87-62a4-4ca9-ba94-46dd1310ebfe

**Comment by alprnbg** [comment]
There is a typo in "Display Login Error" case. It is written "dispay" instead of "display".

**Comment by alprnbg** [comment]
Can you explain to me explicitly the case of "Check User Type to Give Permission for Comment".
Sorry but I don't understand what it means.😄

**Comment by alprnbg** [comment]
Does the "Upload profile" case imply updating the user profile? If so, we should change its name to "Update profile". If not, we should also have a case for updating the profile. Also can you explain what is the "upload profile" case for? By the way, nice job 👍

**Comment by Anxeal** [comment]
The login processes of both a Basic User and a Trader User are the same. Therefore the login nodes should probably be a single node. Also it's possible to login with a Google account, but there's no registration with a Google account, which is the prerequisite for loging in. The rest seem fine other than the points discussed and asked before.

**Comment by safakozdek** [comment]
> Can you explain to me explicitly the case of "Check User Type to Give Permission for Comment".
> Sorry but I don't understand what it means.😄

I think @gokdeemir added that later on, however in my opinion it should not exist in use case diagram because it is not a feature of platform just a minor check that will be done in code. Similar to email check while signing up -it should be an valid email address.-

**Comment by safakozdek** [comment]
> There is a typo in "Display Login Error" case. It is written "dispay" instead of "display".

Fixed.

**Comment by safakozdek** [comment]
> Does the "Upload profile" case imply updating the user profile? If so, we should change its name to "Update profile". If not, we should also have a case for updating the profile. Also can you explain what is the "upload profile" case for? By the way, nice job 👍

Again @gokdeemir added this one, not quite sure what it is about. There could be a typing error.

**Comment by safakozdek** [comment]
> > Can you explain to me explicitly the case of "Check User Type to Give Permission for Comment".
> > Sorry but I don't understand what it means.😄
> 
> I think @gokdeemir added that later on, however in my opinion it should not exist in use case diagram because it is not a feature of platform just a minor check that will be done in code. Similar to email check while signing up -it should be a valid email address.-

Contacted with @gokdeemir . It will be deleted.

**Comment by safakozdek** [comment]
> > Does the "Upload profile" case imply updating the user profile? If so, we should change its name to "Update profile". If not, we should also have a case for updating the profile. Also can you explain what is the "upload profile" case for? By the way, nice job 👍
> 
> Again @gokdeemir added this one, not quite sure what it is about. There could be a typing error.

It's a typing error, I changed it to "update profile". Also "profile help" removed from extension points.
