### ISSUE TITLE
Determination of the sequence diagram scenarios

### ISSUE THREAD

**Issue by SKutayKilic** [bounswe/bounswe2019group7#49]
The scenarios of the sequence diagrams will be determined. There will be 12 different sequence diagrams. After the determination of the sequence diagram titles, the preperation of those diagrams will be distributed and assigned to some subgroups. 

Deadline: 14.03.2019 @ 9.00

**Comment by esrayilmaz7** [comment]
We wrote titles about sequence diagrams below.

**Kemal-Berke:**
- Sign up (Basic User, by using Google account)
- Login (Traders, by using email and password)
- Search a Trading Equipment (Guest,  Trade Indicies)
- Create Comment to Article (Basic User)
- Remove Equipment from Portfolio (Traders)
- Add Equipment to Portfolio (Basic User)

**Merve-Şafak-Alihan:**
- Follow a User (Traders)
- Invest to a Trading Equipment (Traders, Gold)
- Predict on a Trading Equipment (System)
- Make a profile public to private (Basic User)

**Ahmet Emir-Alperen:**
- Create an Alert for a Trading Equipment (Trader)
- Transaction from Bank to User  (System to Trader)
