### ISSUE TITLE
Some sequence diagrams are wrong

### ISSUE THREAD

**Issue by alprnbg** [bounswe/bounswe2019group7#58]
The thick and gray line under the object box should indicate the lifetime of that object. Some sequence diagrams should be corrected by considering this.

**Comment by alprnbg** [comment]
Also, every object box should be a class. For example, "system" is not a object, so it cannot be written on a sequence diagram.

**Comment by safakozdek** [comment]
I realised this in class, I will be changing it this week.

**Comment by safakozdek** [comment]
I updated the sequence diagram that designed by me. Please review follow a user diagram.

**Comment by merveilik** [comment]
Predict and invest sequence diagrams are also updated. Please review them too.

**Comment by kemal-duru-2015400147** [comment]
Sign Up, Search and Delete diagrams are also done. Needs review.

**Comment by Anxeal** [comment]
"Make a profile public to private" updated.

**Comment by nbmetin** [comment]
Login add equipment and share comment to an article are done.

**Comment by safakozdek** [comment]
> "Make a profile public to private" updated.

This is not ok. There is nothing called "Database" in Class Diagram. Please redesign it with respect to class diagram.

**Comment by safakozdek** [comment]
> Sign Up, Search and Remove diagrams are also done.

In Sign up Basic user should be on top like Auth and Guest User... You need to add a bar where basic user stands.

**Comment by liberbey** [comment]
Updated Bank to User Transaction Sequence Diagram.

**Comment by merveilik** [comment]
Responses from one object to another should be with dashed lines, some diagrams need to be fixed. Everyone please check yours.
