### ISSUE TITLE
Slack page

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2019group7#6]
Slack page will be created.

**Comment by Anxeal** [comment]
Slack workspace created. [Invite link](https://join.slack.com/t/bounswe2019group7/shared_invite/enQtNTQ4Njc3MDMzMzQ3LWE5NzUzNWQzYjIxYWRjY2VkY2Q2ZWM5NzcyN2ZlMzAwYzE4ZTU3OGY5N2EzZDI2NmQ2MjdhZjllYWQxM2E5ZmM)
