### ISSUE TITLE
Update Basic User mock-up

### ISSUE THREAD

**Issue by merveilik** [bounswe/bounswe2019group7#61]
On a private profile succes rate and followers/followings count will be shown. Mock-up needs to be updated. 
Deadline: 01.04.2019 @ 09.00

**Comment by nbmetin** [comment]
Success rate is already exist. Did you mean something else?
I added the followers/following count. 
Since, Alihan is not doing anything about this assignment, you don't have to attach him for further issues.

**Comment by merveilik** [comment]
I meant even if the profile is private one shall be able to see success rate and can decide to follow or not. Bill Rashford was a private profile, but now it seems public. Did you changed the scenario?

**Comment by nbmetin** [comment]
I saw the issue just now, so I thought you talking about the new version. You can close the issue, if it's okay now.

**Comment by merveilik** [comment]
I just didn’t realize the change of scenario. New version is ok 👍🏻
