### ISSUE TITLE
Fixing errors on Use Case Diagram

### ISSUE THREAD

**Issue by safakozdek** [bounswe/bounswe2019group7#63]
Errors that stated at the feedback will be revised and necessary changes will be made.

**Comment by safakozdek** [comment]
Feedback Notes

- In use case diagram, how about ranking a comment or article?
- In use case diagram, as far as I can see, "reading articles, events and comments" include "events", which is not true. Correct it.
- In use case diagram, what is system? You don't have such class.
- In use case diagram, for login, instead of include (between login and as a basic and as a trader), you should consider "use case generalization". The same methodology also applies for search traders and search articles.

**Comment by safakozdek** [comment]
I have fixed all errors stated in use case diagram. Please review them @gokdeemir

**Comment by uskudarli** [comment]
@safakozdek seems a good idea to  use the "Needs Review" board in your project.

**Comment by safakozdek** [comment]
> @safakozdek seems a good idea to use the "Needs Review" board in your project.

Thanks for warning, I have just added it.

**Comment by gokdeemir** [comment]
It's reviewed. Some changes are made.
