### ISSUE TITLE
Learning basics of Django

### ISSUE THREAD

**Issue by kemal-duru-2015400147** [bounswe/bounswe2019group7#82]
Everyone will be familiarized with Django which will be used in our API development by implementing a simple task. Deadline : 20.04.2019 23:59

**Comment by SKutayKilic** [comment]
The task is:
Publishing a small web service to AWS which has two endpoints:
1) /messages takes message(string) as a Post request and returns the SHA256 hash digest of that string. 
(That message with it's SHA256 hash digest will be saved to the database)
2) /messages/`<hash>` is a Get request that returns the original message. If `<hash>` does not exists in the database, it will return 404 error.

Notes:
-Django will be used as the framework.
-MySql, Postgresql, or Mongo will be used as the database.

**Comment by alprnbg** [comment]
A nice video series about django, you can check out if you wish.
https://www.youtube.com/playlist?list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK
