### ISSUE TITLE
Implementing getCurrency(), convertCurrency() and makePrediction() functionalities

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2019group7#86]
Implementation of getCurrency(), convertCurrency() and makePrediction() functionalities will be made.

Deadline: 27.04.2019, 23:59

**Comment by liberbey** [comment]
done.

**Comment by alprnbg** [comment]
Needs review

**Comment by safakozdek** [comment]
Currency/views.py
line 9 -- from django.http import JsonResponse --- Unnecessary import, should be deleted.
line 24 -- line is too long it must be at most 120 chars in a line, split the string into 2 pieces and start the second one at next line. Ex: "String" + "String"

Currency/models.py
line 11 --- Add whitespaces before and after operators, change it with this : return str(self.from_currency) + "/" + str(self.to_currency)+": " + str(self.exchange_rate)
