### ISSUE TITLE
Implementation of addToMailList() functionality

### ISSUE THREAD

**Issue by safakozdek** [bounswe/bounswe2019group7#88]
Implementation of addToMailList() functionality will be done.

Deadline: 05.05.2019, 23:59

**Comment by safakozdek** [comment]
After a research I decided to use Mail Chimp to manage mail list. Reasons:

1.  Great dashboard to keep track of new users.
2.  Has functionality to send mail to users that are subscribed to mail List
3.  Ease of use for the one who manage a website.

**Comment by safakozdek** [comment]
I implemented a code that uses Mail Chimp's api to connect the mail list and store the given email in the list.

The code also checks for correctness of email form.
Mailchimp's website: https://mailchimp.com/

**Comment by safakozdek** [comment]
Added tests for url resolving.

**Comment by safakozdek** [comment]
Added tests for form validation

**Comment by safakozdek** [comment]
Unsubscribe options is not implemented since this is a demo app.

**Comment by alprnbg** [comment]
1. Not used libraries in addToMailList/views.py file.
```
from django.shortcuts import render
from rest_framework.decorators import action
```
2. Expected 2 blank lines in line 22 of addToMailList/views.py (PEP 8).
```
def subscribe(email):
    data = {
        "email_address": email,
        "status": "subscribed"
    }
...
```

3. Expected 2 blank lines in line 23 of addToMailList/tests.py (PEP 8).
```
class TestForm2(SimpleTestCase):

    def test_form_is_valid(self):
        form = EmailSignupForm(data={
            'randomName': 'asdasd@gmail.com'
        })
...
```

**Comment by safakozdek** [comment]
Code has been fixed with respect to given feedback. Closing this issue.
