### ISSUE TITLE
Implementation of createArticle(), deleteArticle(), getArticle(), listArticles(), updateArticle() functionalities.

### ISSUE THREAD

**Issue by SKutayKilic** [bounswe/bounswe2019group7#89]
Implementation of createArticle(), deleteArticle(), getArticle(), listArticles(), updateArticle() functionalities will be done.

Deadline: 29.04.2019, 09:00

**Comment by SKutayKilic** [comment]
Done

**Comment by safakozdek** [comment]
I will be reviewing the code. Will post results to here.

**Comment by safakozdek** [comment]
1.Article/views.py
line 42 --  print('aa')  --- This should be removed.

2.Article/models.py
line 2 -- from django.contrib.auth.models import User --- This import looks unnecessary, should be removed.

line 3-4  --- There should be 2 empty lines before a class implementation as PEP-8 suggests. Add 1 more empty line, there is only 1 empty line between class and imports.

3.Article/serializer.py 
Same thing -- Add 1 more empty line between imports and class.

4. Article/tests.py
Please add unit tests. Useful link: https://www.youtube.com/playlist?list=PLbpAWbHbi5rMF2j5n6imm0enrSD9eQUaM
