### ISSUE TITLE
Work Done by Each Member	

### ISSUE THREAD

**Issue by gokdeemir** [bounswe/bounswe2019group7#97]
Work Done by Each Member of milestone will be prepared. After that Berke will convert it to table.
Deadline: 11.05.2019, 23:59

**Comment by alprnbg** [comment]
If it is okey for you @nbmetin, we can gather what we wrote here.

**Comment by alprnbg** [comment]
we can close the issue, because everyone wrote

**Comment by alprnbg** [comment]
The table part has not been done yet, sorry 😄
